FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1

# Запуск Celery worker
CMD ["celery", "-A", "BrainTumor", "worker", "--loglevel=info"]
