services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  web:
    build: .
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "44444:8000"
    networks:
      - mynetwork

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    container_name: django_celery
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    networks:
      - mynetwork

  yoloserver:
    build: ./yolo  # Путь к папке с Dockerfile YOLO
    container_name: yoloserver
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - "8001:8001"
    volumes:
      - .:/workspace       # весь проект
      - ./media:/workspace/media  # доступ к /media, если YOLO это нужно явно
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
