version: "3.8"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  redis:
    image: redis:7
    container_name: redis
    restart: always
    networks:
      - mynetwork
    ports:
      - "6379:6379"

  web:
    image: ffffakel17/web:latest
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "44444:8000"
    networks:
      - mynetwork

  celery:
    image: ffffakel17/celery:latest
    container_name: django_celery
    restart: always
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - ./media:/app/media
    networks:
      - mynetwork

  yoloserver:
    image: ffffakel17/yoloserver:latest
    container_name: yoloserver
    ports:
      - "8001:8001"
    volumes:
      - ./yolo:/workspace/yolo
      - ./media:/workspace/media
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
