# Generated by Django 5.1.6 on 2025-03-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина'), ('other', 'Другое')], max_length=10, verbose_name='Пол')),
                ('doctor_name', models.TextField(verbose_name='Имя врача')),
                ('doctor_diagnosis', models.TextField(verbose_name='Диагноз врача')),
                ('neural_diagnosis', models.TextField(verbose_name='Диагноз нейросети')),
                ('server_path', models.TextField(verbose_name='Путь к данным')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
    ]
