# Generated by Django 5.1.6 on 2025-06-07 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebSite', '0002_patient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataModel',
        ),
    ]
